# Site settings
title: Dominion League
email: dominionleague@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The Dominion League is a free online tournament for competitive Dominion at all skill levels.
baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://www.dominionleague.org" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
# permalink: pretty
plugins:
  - jekyll-paginate
# for rules changelog
collections:
  rules:
    output: true

# paginate: 4
# paginate_path: "blog/page:num"
